version: '3'

services:
  mbapp:
    build: .
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mbapp

  redis:
    image: redis:latest
    restart: always