# Generated by Django 4.2 on 2023-04-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="location",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="business",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
